#!/usr/bin/env bash

echo "Deploy cfn import stack..."

STACK_NAME="import-stack"

aws cloudformation deploy \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-1
