#!/usr/bin/env bash

echo "Deploy cfn prevent stack update..."

STACK_NAME="prevent-stack-update"

aws cloudformation deploy \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-1
