AWSTemplateFormatVersion: "2010-09-09"
Description: My CloudFormation Stack Update Template
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02457590d33d576c3
      InstanceType: t2.micro
