#!/usr/bin/env bash

echo "Deploy cfn depends on stack..."

STACK_NAME="depends-on-stack"

aws cloudformation deploy \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-1
