AWSTemplateFormatVersion: "2010-09-09"
Description: My CloudFormation Stack - Depends on EC2 Instances - Create in the order 2, 3 and then 1.
Resources:
  MyEC2Instance1:
    Type: AWS::EC2::Instance
    DependsOn: MyEC2Instance3
    Properties:
      ImageId: ami-02457590d33d576c3
      InstanceType: t2.micro
  MyEC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02457590d33d576c3
      InstanceType: t2.micro
  MyEC2Instance3:
    Type: AWS::EC2::Instance
    DependsOn: MyEC2Instance2
    Properties:
      ImageId: ami-02457590d33d576c3
      InstanceType: t2.micro
