#!/usr/bin/env bash

echo "== Deploying RDS Instance"

STACK_NAME="rds=basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--parameter-overrides ParameterKey1=ParameterValue1 \
--stack-name $STACK_NAME
