terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.0.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "default" {
  # Optional: specify bucket name or leave blank for autogenerated
  # bucket = "my-unique-bucket-name"
}

resource "aws_s3_object" "object" {
  bucket = aws_s3_bucket.default.id
  key    = "hello.txt"
  source = "hello.txt"
  etag   = filemd5("hello.txt")
}
