#!/usr/bin/env bash

echo "== deploy sns"

STACK_NAME="sns-basic"

# Check if AWS credentials are configured
if ! aws configure list &> /dev/null; then
    echo "AWS credentials are not configured. Please configure them and try again."
    exit 1
fi

# Deploy the CloudFormation template
aws cloudformation deploy \
    --template-file template.yaml \
    --stack-name $STACK_NAME \
    --capabilities CAPABILITY_NAMED_IAM \
    --no-execute-changeset \
    --region us-east-1

# Check if the deployment was successful
if [ $? -eq 0 ]; then
    echo "Deployment successful."
else
    echo "Deployment failed."
fi
