#!/usr/bin/env bash

echo "Deploying drift detection stack..."

STACK_NAME="drift-detection-ec2"

aws cloudformation deploy \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--template-file template.yaml \
--region us-east-1 \
--no-execute-changeset
