#!/bin/bash
echo "deploying datastreams..."

STACK_NAME="datastreams"

aws cloudformation deploy \
    --template-file template.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --no-execute-changeset \
    --region us-east-1 \
    --stack-name $STACK_NAME
