AWSTemplateFormatVersion: "2010-09-09"
Description: My CloudFormation Stack Update Template
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to store the stack update artifacts.
    Default: my-stack-update-bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
