#!/bin/bash

echo "== Deploying Cloud9 environment"

STACK_NAME="aws-cloud9-environment"

aws cloudformation deploy \
--template-file template.yaml \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1
